In [34]:
a=int(input())
b=int(input())
print(f"a + b = {a+b}")
print(f"a - b = {a-b} and b - a = {b-a}")
print(f"a * b = {a*b}")
#input: 15, 24


a + b = 39
a - b = -9 and b - a = 9
a * b = 360


In [30]:
a=int(input())
print(a%10)
#input 12345

5


In [31]:
a, b = list(map(int, input().split()))
print((a*b)**0.5)
#input: 4, 2

2.8284271247461903


In [28]:
file = open('input.txt','r')
numbers = list(map(int, file.readline().split()))
#print (numbers)
znak = file.readline()
file.close()
t = numbers[0]

if znak=='+':
    for i in range(1, len(numbers)):
        t=t+numbers[i]
if znak=='-':
    for i in range(1, len(numbers)):
        t=t-numbers[i]
if znak=='*':
    for i in range(1, len(numbers)):
        t=t*numbers[i]    

file = open('output.txt', 'w')
file.write(str(t))
file.close()

In [23]:
def convert(num, basefrom, baseto):
    if num >= 0:
        sign = 1
    else:
        sign = -1
        num = num * (-1)
    temp = 0
    i = 0
    while num > 0:
        temp += (num % 10 * (basefrom ** i))
        i += 1
        num //= 10
    temp2 = []

    
    while temp > 0:
        temp2.append(temp % baseto)
        temp //= baseto
    returned = 0
    for i in range (len(temp2)):
        returned += temp2[i]*(10**i)
    return returned*sign
    
print('введите каждое число в отдельной строке')
n = int(input())
b = int(input())
c = int(input())
print(convert(n, b, c))

#input -110101101, 2, 8

введите каждое число в отдельной строке
-655


In [26]:
def convert(num, basefrom, baseto):
    if num >= 0:
        sign = 1
    else:
        sign = -1
        num = num * (-1)
    temp = 0
    i = 0
    while num > 0:
        temp += (num % 10 * (basefrom ** i))
        i += 1
        num //= 10
    temp2 = []

    
    while temp > 0:
        temp2.append(temp % baseto)
        temp //= baseto
    returned = 0
    for i in range (len(temp2)):
        returned += temp2[i]*(10**i)
    return returned*sign


file = open('input.txt', 'r')
numbers = list(map(int, file.readline().split()))
znak = file.readline()
base = int(file.readline())
file.close()

#print(numbers, znak, base)
for i in range(len(numbers)):
    numbers[i] = convert(numbers[i], base, 10)
t = numbers[0]
if znak=='+\n':
    for i in range(1, len(numbers)):
        t=t+numbers[i]
if znak=='-\n':
    for i in range(1, len(numbers)):
        t=t-numbers[i]
if znak=='*\n':
    for i in range(1, len(numbers)):
        t=t*numbers[i]
t = convert(t, 10, base)

file = open('output.txt', 'w')
file.write(str(t))
file.close()


In [32]:
#3. Create a null vector of size 10
import numpy as np
a = np.zeros(10)

print (a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [33]:
#12. Create a 3x3x3 array with random values
import numpy as np
a = np.random.rand(3, 3, 3)

print (a)

[[[0.79671978 0.69102692 0.37275677]
  [0.22938808 0.28943431 0.67244263]
  [0.86000504 0.96380917 0.79559728]]

 [[0.32227174 0.3056834  0.66618408]
  [0.13991965 0.27090656 0.91906029]
  [0.22515524 0.92623737 0.09657669]]

 [[0.66634336 0.61844066 0.50396029]
  [0.71651776 0.65298221 0.91949696]
  [0.32025501 0.03597931 0.08793513]]]


In [44]:
#21. Create a checkerboard 8x8 matrix using the tile function
import numpy as np
a = np.array([0, 1])
b = np.array([1, 0])
c = np.tile(a, (1, 4))
d = np.tile(b, (1, 4))
e = np.vstack([c, d])
result = np.tile(e, (4, 1))
print(result)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [58]:
#33. How to get the dates of yesterday, today and tomorrow?
import numpy as np
today = np.datetime64('today')
print (today)
yesterday = np.datetime64('today') - np.timedelta64(1)
print(yesterday)
tomorrow = yesterday = np.datetime64('today') + np.timedelta64(1)
print (tomorrow)

2024-09-08
2024-09-07
2024-09-09


In [74]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 
import numpy as np
a = np.random.rand(10, 2)

print(a)
print('\n\n')
b = np.zeros([10, 2])

for i in range(10):
    b[i,0] = np.sqrt(a[i,0]**2+a[i,1]**2)
    b[i,1] = np.arctan(a[i,1]/a[i,0])

print(b)

[[0.3383623  0.0693046 ]
 [0.78713305 0.30732155]
 [0.00905789 0.2468467 ]
 [0.36174712 0.68314212]
 [0.7071001  0.5236618 ]
 [0.64034537 0.4400833 ]
 [0.49548488 0.59764842]
 [0.61897497 0.98914192]
 [0.48261885 0.49360823]
 [0.46104405 0.7817547 ]]



[[0.34538699 0.20202935]
 [0.84499999 0.37223057]
 [0.24701283 1.53411839]
 [0.77300979 1.08380146]
 [0.87989331 0.63744281]
 [0.77699132 0.60212387]
 [0.77633041 0.87858683]
 [1.16684693 1.01164377]
 [0.69034053 0.79665468]
 [0.90758031 1.03794369]]


In [110]:
#58. Subtract the mean of each row of a matrix

import numpy as np

a = np.random.rand(6, 6)
print (a)

b = a - a.mean(axis=1, keepdims=True)
print (b)


[[0.46532186 0.94163522 0.44859828 0.08882009 0.90950519 0.72127505]
 [0.71694425 0.01988448 0.45627922 0.67551004 0.34512701 0.59726712]
 [0.55245082 0.05249432 0.40494692 0.97050615 0.73494876 0.50162849]
 [0.61892576 0.35824023 0.85201496 0.13224548 0.80328931 0.67653939]
 [0.72109939 0.75757033 0.48623655 0.35848854 0.26233992 0.82553846]
 [0.47139068 0.70415035 0.63639159 0.00314806 0.04674389 0.07690755]]
[[-0.13053742  0.34577594 -0.147261   -0.50703919  0.3136459   0.12541577]
 [ 0.24844223 -0.44861754 -0.0122228   0.20700802 -0.12337501  0.1287651 ]
 [ 0.01628824 -0.48366825 -0.13121566  0.43434357  0.19878619 -0.03453409]
 [ 0.04538324 -0.21530229  0.27847244 -0.44129704  0.22974679  0.10299687]
 [ 0.15255386  0.1890248  -0.08230898 -0.21005699 -0.30620561  0.25699293]
 [ 0.14826866  0.38102833  0.31326957 -0.31997396 -0.27637813 -0.24621447]]


In [127]:
#61.  Find the nearest value from a given value in an array
import numpy as np 
val = float(input())
a = np.random.rand(10)
print (a)
idx = (np.abs(a - val)).argmin()
print(a[idx])
print(idx)



[0.82011512 0.6651461  0.73613568 0.05697421 0.85469387 0.59821742
 0.38197761 0.80642544 0.98569709 0.12502132]
0.3819776066489827
6


In [137]:
#72. How to swap two rows of an array?
import numpy as np
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12],[13, 14, 15]])
print(a)
a = a[[0, 2, 1, 3, 4]]
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]
 [13 14 15]]


In [2]:
#83. How to find the most frequent value in an array?
import numpy as np
a = np.array([1, 2, 3, 4, 5, 2, 3, 4, 5, 3, 4, 5, 4, 4])
print(np.bincount(a).argmax())

4


In [6]:
#96. Given a two dimensional array, how to extract unique rows? (★★★)
import numpy as np
a = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5], [2, 3, 4], [6, 7, 8]])
print(a)
print('\n')
b = np.unique(a, axis=0)

print(b, sep='\n')

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [2 3 4]
 [6 7 8]]


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [6 7 8]]
